name: Build
on: 
  push:
    branches:
      - main
    paths:
      - "src/**.c"
      - ".github/workflows/build.yml"
      - "Makefile"
strategy:
  matrix:
    compiler: []
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install -y build-essential make git
          sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          git clone --depth 1 https://github.com/raysan5/raylib.git raylib
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install
      - name: Compile
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux binaries
          path: bin/*
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [clang]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          mkdir w64devkit
          Invoke-WebRequest -Uri 'https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-1.23.0.zip' -OutFile 'w64devkit.zip'
          Invoke-WebRequest -Uri 'https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw-w64.zip' -OutFile 'raylib.zip'
          tar -xf raylib.zip
          tar -xf w64devkit.zip
          mv raylib-5.5_win64_mingw-w64/include/* w64devkit/x86_64-w64-mingw32/include/
          mv raylib-5.5_win64_mingw-w64/lib/* w64devkit/x86_64-w64-mingw32/lib/
          $Env:PATH += ";%cd%/w64devkit/bin"
      - name: Compile
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows binaries
          path: bin/*
